#!/bin/sh
# Copyright (C) zhao

if [ $UID -ne 0  ]; then
    echo "root user are required to run this script" 
    exit 1;
fi

passwd="Nbppassw0rd"
SFTP=sftp
WWW=www
NBPVG=nbpvg
NBPVG_PASSWD=${NBPVG_PASSWD:-$passwd}
NBPDOWN=nbpdown
NBPDOWN_PASSWD=${NBPDOWN_PASSWD:-$passwd}
NBPWWW=nbpwww
NBPWWW_PASSWD=${NBPWWW_PASSWD:-$passwd}
SFTP_HOME=/home/sftp/NBP_AAS
NBPVG_HOME=$SFTP_HOME"/vg_upload"

#create group if not exists
grep "$SFTP" /etc/group >& /dev/null
if [ $? != 0 ]; then
	echo -e "add user group: "$SFTP
	groupadd $SFTP
fi

grep "$WWW" /etc/group >& /dev/null
if [ $? != 0 ]; then
	echo -e "add user group: "$WWW
	groupadd $WWW
fi

#create home directory if not exists
if [ -d $SFTP_HOME ]; then
	echo -e "create home directory: "$SFTP_HOME
	mkdir -p $SFTP_HOME
fi

if [ -d $NBPVG_HOME ]; then
	echo -e "create home directory: "$NBPVG_HOME
	mkdir -p $NBPVG_HOME
fi

#create user if not exists
grep "$NBPVG" /etc/passwd >& /dev/null
if [ $? != 0 ]; then
	echo -e "add user: "$NBPVG
	useradd -d $SFTP_HOME -g $SFTP -M -s /sbin/nologin -p $NBPVG_PASSWD $NBPVG
fi

grep "$NBPDOWN" /etc/passwd >& /dev/null
if [ $? != 0 ]; then
	echo -e "add user: "$NBPDOWN
	useradd -d $SFTP_HOME -g $SFTP -G $WWW -M -s /sbin/nologin -p $NBPDOWN_PASSWD $NBPDOWN
fi

grep "$NBPWWW" /etc/passwd >& /dev/null
if [ $? != 0 ]; then
	echo -e "add user: "$NBPWWW
	useradd -d $SFTP_HOME -g $WWW -M -s /sbin/nologin -p $NBPWWW_PASSWD $NBPWWW
fi

#check user 
grep "$NBPVG" /etc/passwd >& /dev/null
if [ $? != 0 ]; then
	echo -e $TEST_FAIL"user: "$NBPVG" create failed"
	exit 1;
fi

grep "$NBPDOWN" /etc/passwd >& /dev/null
if [ $? != 0 ]; then
	echo -e $TEST_FAIL"user: "$NBPDOWN" create failed"
	exit 1;
fi

grep "$NBPWWW" /etc/passwd >& /dev/null
if [ $? != 0 ]; then
	echo -e $TEST_FAIL"user: "$NBPWWW" create failed"
	exit 1;
fi

